version: '3.1'

services:

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
    - "3306:3306"



  myapi:
    build: ./
    restart: always
    ports:
    - "8081:8081"
    depends_on:
      - mysql
    links:
      - mysql:db
