version: '3.1'

services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD : "password123"
      MYSQL_DATABASE : "test"
    ports:
    - "3306:3306"

#  elasticsearch:
#    image: elasticsearch:6.4.2
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      - http.host=elasticsearch
#      - transport.host=0.0.0.0
#      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  rabbitmq-server:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq-server"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  myapi:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq-server
    links:
      - mysql
      - rabbitmq-server

  postapi:
    build: /Users/gaurav/go/src/github.com/cocoagaurav/httpHandler/Post
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - myapi
      - rabbitmq-server
    links:
      - mysql
      - myapi
      - rabbitmq-server

  scrapapi:
    build: /Users/gaurav/go/src/github.com/cocoagaurav/httpHandler/scrap
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq-server
      - myapi
    links:
      - rabbitmq-server