version: '3.1'

services:

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: test
    ports:
    - "3306:3306"

  myapi:
    build: ./
    ports:
    - "8081:8081"
    depends_on:
      - mysql
    links:
      - mysql
