apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: myapi
  name: myapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myapi
    spec:
      containers:
      - image: gauravcococadocker/myapi
        name: myapi
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
