apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapi
spec:
  replicas: 1
    spec:
      containers:
      - image: myapi
        name: myapi
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
