apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: myapi
  name: myapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myapi
    spec:
      containers:
      - image: gauravcococadocker/myapi
        name: myapi
        ports:
        - containerPort: 8080
    env:
    - name: myapi_Sql_Url
      value: "root:password123@tcp(mysql:3306)/test?charset=utf8&parseTime=True&loc=Local"
    - name: myapi_rabbit_Url
      value: "amqp://guest:guest@rabbitmq-server:5672/"
    - name: myapi_firebase_service_Id
      value:  "firebase-adminsdk-6b9tl@testproject-fa267.iam.gserviceaccount.com"
        resources: {}
      restartPolicy: Always
status: {}
